version: "3.7"
services:
  go_barber_api:
    container_name: go_barber_api
    hostname: go_barber_api
    restart: unless-stopped
    expose:
      - "3333"
    ports:
      - "3333:3333"
    entrypoint:
      - sh
      - go-barber-entrypoint.sh
    volumes:
      - go_barber:/app/
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - gobarber
    depends_on:
      - postgresql
      - redis
      - mongo

  postgresql:
    container_name: postgres
    networks:
      - gobarber
    ports:
      - "5432:5432"
    build:
      context: ../docker/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      GO_BARBER_DB: gobarber
    volumes:
      - postgresql:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - gobarber
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - gobarber
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  go_barber:
  postgresql:
  mongo:
  redis:

networks:
  gobarber:
    driver: bridge


