name: Dev Workflow - Test and Build Application

on:
  pull_request:
    branches: [develop]
jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Enviroment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
          check-latest: true
      - run: cp .env.example .env.test

      - name: Setup Cache Dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run Unit Tests
        run: yarn test

      - name: Run Build
        run: yarn build
