name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      
      # Instalar as dependências NPM/Yarn
      - name: Install dependencies
        run: yarn
        
      # Executar a build
      - name: Run build
        run: yarn build
        
      - name: Copy build dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist,tmp,.env,package.json,ormconfig.json,yarn.lock"
          target: "app"
      
      # Copiar a pasta dist para dentro da Digial Ocean
      # Executar yarn na Digital Ocean
      # Executar migrations
